### ISSUE TITLE
SPIKE: how to move off of production db

### ISSUE THREAD

**Issue by lauraGgit** [18F/identity-analytics-etl#192]
## User story

As a user, I would like to not have my information manipulated, so that I can trust login.gov.

## Notes

**What is the value to the user in this story?**
- following least privilege for our analytics
- read only
- increasing stability of production

**What are things we should consider when making this story**
- 

## Acceptance Criteria

- [ ] is determine a strategy to mitigate that
- [ ] shouldn't be possible write to production db for analytics query
- [ ] minimal performance implications of the prod app
- [ ] not raising concerns to devops folks about long running queries

**Comment by MacHu-GWU** [comment]
Available Solution:

- Add one more replica and make IDP app not first reading / writing from it. Since RDS use eventually consistency strategy, Data could be up to seconds / minutes of behind. 
- Take snapshot periodically (every day) and make a clone database. Data could be up to 1 day behind.

@lauraGgit the DB is more about Devops work (I think the DBA is part of our Devops team), we need a meeting with Devops.

**Comment by lauraGgit** [comment]
@MacHu-GWU can you say a bit more about what you mean about "*DP app not first reading / writing from it"?

**Comment by MacHu-GWU** [comment]
@lauraGgit, Separate Read / Write is a common strategy to balance the workload. For example a db cluster usually have 3 notes a, b, c. We assume that <a> for write (app try with node a first, if failed then try node <b>), and <b> for read, <c> for redundant. When there is a write operation, it goes to <a>, and new data is [eventually available (see the AWS RDS internal implementation doc)](https://aws.amazon.com/blogs/aws/amazon-rds-announcing-read-replicas/) from <b>, then <c>.

**My point is, analytics may query from <c> (with data delay), but App prefer read from <b> than <c>.**
